name: Alerta Push Main

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: Nuevo Push en Main" \
               -H "Priority: default" \
               -d "Se realizó un push al repositorio ${{ github.repository }} por ${{ github.actor }}. Commit: ${{ github.sha }}" \
               https://ntfy.sh/devops-itla