name: CI y Alerta

on:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install flake8 pytest

      - name: Linting
        run: |
          flake8 . --count --statistics

      - name: Ejecutar pruebas unitarias
        run: |
          pytest -v

  notificar:
    runs-on: ubuntu-latest
    needs: validar

    steps:
      - name: Enviar notificación a ntfy
        run: |
          curl -H "Title: CI Exitosa" \
               -H "Priority: default" \
               -d "Push validado correctamente en ${{ github.repository }} por ${{ github.actor }}" \
               https://ntfy.sh/devops-itla